version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations categories &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /app # This should only specify the container path
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=categories_task
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=1234

  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=categories_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

volumes:
  postgres_data:
